# SPDX-License-Identifier: GPL-3.0-or-later
# Stable rustfmt (1.85) only honours a small set of options without `unstable_features`.
edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
reorder_imports = true
reorder_modules = true
